### ISSUE TITLE
Missing bindata

### ISSUE THREAD

**Issue by Pitel** [Seriell/RC24-MailPatch-Portable#3]
```
/tmp/Mail-Patch-Portable-1.0.1-linux-x86_64/lib/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bindata (LoadError)
	from /tmp/Mail-Patch-Portable-1.0.1-linux-x86_64/lib/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/Mail-Patch-Portable-1.0.1-linux-x86_64/lib/app/mailparse.rb:6:in `<module:MailParse>'
	from /tmp/Mail-Patch-Portable-1.0.1-linux-x86_64/lib/app/mailparse.rb:5:in `<module:SerieBot>'
	from /tmp/Mail-Patch-Portable-1.0.1-linux-x86_64/lib/app/mailparse.rb:3:in `<main>'
```

**Comment by Erisa** [comment]
Hi there, thanks for creating an issue.
Could you please tell me more about your environment (Linux Distro, CPU architecture, etc.) and I can try and work out the cause.

**Comment by Pitel** [comment]
Ubuntu 17.10 64bit

**Comment by umer936** [comment]
Also having the same issue on `Ubuntu 17.10 64bit` running the `Mail-Patch-Portable-1.0.1-linux-x86_64.tar.gz` release. 

`sudo apt install ruby-bindata` does not fix (haven't touched Ruby much, but makes sense if I'm understanding how it's packaged correctly).

**Comment by Erisa** [comment]
Installing bindata from apt wouldn't change things because this application
uses its own local version which it can't seem to find for some reason.
I think this is an upstream problem with Travelling Ruby itself, I'll do
some more investigation at some point to try and work it out.

**Comment by ItchyBugReporter** [comment]
I'm seeing this on Devuan Jessie 32bit.

**Comment by coffeverton** [comment]
Same here on Debian Jessie 64bit

**Comment by spotlightishere** [comment]
(This repository hasn't been updated due to a lack of traveling ruby updates, and both developers working on it have left the project. I believe @RiiConnect24's bot still has a working patch feature, that may be of interest.)
